[project]
name = "aedg-metadata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "frictionless>=5.18.0",
    "oemetadata>=2.0.3",
    "pyyaml>=6.0.2",
]
