resource:
  name: "public_communities_monthly_generation"
  title: "Monthly electrical generation by community"
  description: >
      Monthly electrical generation is aggregated by grid
      and associated with every community connected to the grid.
  path: "https://raw.githubusercontent.com/acep-aedg/aedg-data-pond/refs/heads/main/data/public/public_communities_monthly_generation.csv"
  keywords:
    - generation
    - electricity
    - fuel type
    - grid
    - intertie
    - reports
    - Power Cost Equalization (PCE)
    - EIA Form 923
  topics:
    - Electricity
  source:
    - dcra.communities
    - dol.places
    - acep.es_generation
  licenses:
    - CC-SA-4.0
  spatial:
    name: Alaska
    boundingBox: [-187.55, 51.21, -130.0, 71.35]
    crs: OGC:CRS84
  temporal:
    referenceDate: "2025-01-01"  # equivalent to as_of_date
    timeseries:  # is a list of possibly multiple time periods
      -
        start: "2021-01"
        end: "2021-12"
        resolutionValue: "1"
        resolutionUnit: month
        alignment: null
        aggregationType: sum
  fields: # column names
    - fips_code
    - grid_id
    - name
    - net_generation_mwh
    - fuel_type
    - year
    - month
  primaryKey: # An array of fields that uniquely identifies each row in the table
    - grid_id
    - fuel_type
    - year
    - month
