resource:
  name: "public_communities_monthly_generation"
  title: "Monthly electrical generation by community"
  description: >
      Monthly electrical generation is aggregated by grid
      and associated with every community connected to the grid.
  path: "https://github.com/acep-aedg/aedg-data-pond/blob/main/data/public/public_communities_monthly_generation.csv"
  keywords:
    - "generation"
    - "foo"
    - "bar"
  topics: ["Electricity"]
  licenses: ["CC0-1.0"]
  spatial:
    name: Alaska
    boundingBox: [-187.55, 51.21, -130.0, 71.35]
    crs: OGC:CRS84
  temporal:
    referenceDate: "2025-01-01"  # equivalent to as_of_date
    timeseries:
      -
        start: "2021-01"
        end: "2021-12"
        resolutionValue: "1"
        resolutionUnit: month
        alignment: null
        aggregationType: sum
#      -
#        start: "2025-03"
#        end: null
#        resolutionValue: null
#        resolutionUnit: null
#        alignment: null
#        aggregationType: null
  fields:
    - fips_code
    - grid_id
    - name
    - net_generation_mwh
    - fuel_type
    - year
    - month
