resource:
  name: public_communities_population # Filename stub
  title: Community Total Population # Dataset title
  summary: | # Short version of the description to appear in data explorer list
    Summary of the total population of each community.
  description: | # Description of what this dataset is and what it is doing here
    Total populations were measured by the U. S. Census and associated with communities by the Alaska Department of Labor and Workforce Development.
  path: "https://raw.githubusercontent.com/acep-aedg/aedg-data-pond/refs/heads/main/data/public/public_communities_population.csv" # link to dataset in GitHub
  keywords: # list of keywords and short phrases, limit 10
    - total population
    - census
  topics: # 1-2 broad topics for display in AEDG (which not all datasets need?)
    - Social
  publisher: acep
  sources: # list of directory names in https://github.com/acep-aedg/aedg-etl-2024/tree/main/data-sources to get source.yml
    - dol.places
    - dcra.communities
  licenses: # list of keys in the license.yml registry
    - CC-SA-4.0
  spatial:
    name: Alaska
    boundingBox: [-187.55, 51.21, -130.0, 71.35]
    crs: OGC:CRS84
  temporal:
    referenceDate: "2020-01-01"  # equivalent to as_of_date
    timeseries: null # is a list of possibly multiple time periods
  fields: # list of column names in the dataset linking to fields.csv registry
    - fips_code
    - name
    - total_population
    - year
  primaryKey: # list of the fields that uniquely identifies each row in the table
    - fips_code
    - year
  contributors: # who helped make the dataset
    - organization: acep
      roles:
        - DataCurator
      date: now
      object: data via https://github.com/acep-aedg/aedg-etl-2024
      comment: |
        1. Identified data source and integrated it into the data pipeline.
        2. Complied community names, locations, and FIPS identifiers for AEDG
        3. Joined population data with AEDG communities to create this dataset
