name: "Sphinx: Render docs"

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
        - name: Install dependencies
          run: |
            pip install sphinx sphinx_rtd_theme myst_parser pydata-sphinx-theme sphinx-autoapi
        - name: Install Barlow font
          run: |
            mkdir -p ~/.local/share/fonts
            wget -qO- https://github.com/google/fonts/raw/main/ofl/barlow/Barlow-Regular.ttf > ~/.local/share/fonts/Barlow-Regular.ttf
            wget -qO- https://github.com/google/fonts/raw/main/ofl/barlow/Barlow-Bold.ttf > ~/.local/share/fonts/Barlow-Bold.ttf
            fc-cache -f -v
        - name: Sphinx build
          run: |
            cd docs
            make html
        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          with:
            publish_branch: gh-pages
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: docs/_build/html/
            force_orphan: true
